In [1]:
import numpy as np

# 넘파이 배열의 구조

- 넘파이 모듈의 기본 배열은 ndarray(n-dimension array, 다차원배열)

## 리스트를 다차원배열로 변환

In [2]:
# array() : 다차원배열을 만드는 함수
lst = [1, 2, 3, 4]
lst_array = np.array(lst)

In [3]:
lst_array

array([1, 2, 3, 4])

In [4]:
type(lst_array)

numpy.ndarray

## 튜플을 다차원배열로 변환

In [5]:
tu = (1, 2, 3, 4)
tu_arr = np.array(tu)

In [6]:
tu_arr

array([1, 2, 3, 4])

In [7]:
type(tu_arr)

numpy.ndarray

In [9]:
# 배열은 mutable 의 특징을 가짐
# 변수를 다른 변수에 복사한 뒤 데이터를 수정하면 모든 변수의 데이터가 수정됨
co_arr = lst_array
id(co_arr), id(lst_array)

(2385360225840, 2385360225840)

In [10]:
co_arr[0] = 100

In [11]:
co_arr

array([100,   2,   3,   4])

In [12]:
lst_array

array([100,   2,   3,   4])

In [13]:
# 다차원 배열의 값을 복사해서 새로운 배열을 만들면
# 동일한 값을 가진 새로운 배열이 만들어지기 때문에 서로 다른 데이터가 됨
new_arr = np.array(lst_array)

In [14]:
id(new_arr), id(lst_array)

(2385375412944, 2385360225840)

In [15]:
new_arr[0] = 99

In [16]:
new_arr

array([99,  2,  3,  4])

In [17]:
lst_array

array([100,   2,   3,   4])

## 자료형을 지정해서 다차원 배열 만들기

- 파이썬 리스트는 다양한 자료형을 사용할 수 있지만 넘파이 배열은 같은 자료형만 넣을 수 있음
    - 다차원 배열을 생성할 때 자료형을 지정하지 않으면 내부의 원소를 보고 자동으로 추론해서 만듦

In [22]:
# float 자료형을 지정해서 다차원 배열 만들기
fl_arr = np.array(lst, dtype = float)

In [23]:
fl_arr

array([1., 2., 3., 4.])

In [24]:
fl_arr.dtype

dtype('float64')

# 2차원 배열

- 2개의 축을 가지는 배열(행, 열)
    - 두 개의 1차원 배열이 쌓여서 하나의 2차원 배열이 만들어짐

In [25]:
arr2d = np.array([[1, 2, 3], [4, 5, 6]])

In [26]:
arr2d

array([[1, 2, 3],
       [4, 5, 6]])

In [27]:
# 각 축의 원소의 개수
arr2d.shape

(2, 3)

In [28]:
# 축의 개수
arr2d.ndim

2

In [29]:
arr2d.dtype

dtype('int32')

In [30]:
# 다차원 배열을 1차원 배열로 조회
arr2d.flatten()

array([1, 2, 3, 4, 5, 6])

In [31]:
arr2d

array([[1, 2, 3],
       [4, 5, 6]])

# 원소 조회하기

In [32]:
# 1차원 배열에서 원소 조회하기
lst_array

array([100,   2,   3,   4])

In [33]:
lst

[1, 2, 3, 4]

In [34]:
lst[0]

1

In [35]:
lst_array[0]

100

In [36]:
# 다차원배열에서 원소 조회하기
list2d = arr2d.tolist() # 배열을 리스트로 변환

In [37]:
list2d

[[1, 2, 3], [4, 5, 6]]

In [39]:
arr2d

array([[1, 2, 3],
       [4, 5, 6]])

In [42]:
# 리스트는 정수만 이용해서 원소 조회 가능
# 따라서 리스트 내 리스트의 원소를 조회할 때는 인덱스를 두 번 사용해야함
list2d[0][1]

2

In [43]:
list2d[0, 1]

TypeError: list indices must be integers or slices, not tuple

In [48]:
# 다차원 배열은 행과 열의 인덱스를 튜플로 조회할 수 있음
arr2d[0, 1]

2

In [47]:
arr2d[0][1]

2

## 슬라이싱

In [49]:
arr1 = np.array([[0, 1, 2, 3],
                 [4, 5, 6, 7]])

In [50]:
arr1

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [51]:
# 첫 번째 행 전체
arr1[0, :]

array([0, 1, 2, 3])

In [52]:
# 두 번째 열 전체
arr1[:, 1]

array([1, 5])

In [53]:
# 두 번째 행의 두 번째 열부터 끝 열까지
arr1[1, 1:]

array([5, 6, 7])

In [54]:
# 각 행의 두 번째 열까지
arr1[:, :2]

array([[0, 1],
       [4, 5]])

- 연습문제

1. 아래의 행렬에서 값 7을 인덱싱

2. 아래의 행렬에서 값 14를 인덱싱

3. 아래의 행렬에서 배열 [6, 7] 을 슬라이싱

4. 아래의 행렬에서 배열 [7, 12] 를 슬라이싱

5. 아래의 행렬에서 배열 [[3, 4], [8, 9]] 를 슬라이싱

In [55]:
m = np.arange(15).reshape(3, -1)

In [56]:
m

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [59]:
# 1. 아래의 행렬에서 값 7을 인덱싱
m[1, 2]

7

In [61]:
# 2. 아래의 행렬에서 값 14를 인덱싱
m[2, -1]

14

In [62]:
# 3. 아래의 행렬에서 배열 [6, 7] 을 슬라이싱
m[1, 1:3]

array([6, 7])

In [63]:
# 4. 아래의 행렬에서 배열 [7, 12] 를 슬라이싱
m[1:, 2]

array([ 7, 12])

In [64]:
# 5. 아래의 행렬에서 배열 [[3, 4], [8, 9]] 를 슬라이싱
m[:2, 3:]

array([[3, 4],
       [8, 9]])

## 파이썬 리스트와 넘파이 배열의 차이

- 넘파이 배열은 배열끼리 연산이 가능하지만 파이썬 리스트는 값의 추가만 가능

- 넘파이 배열은 숫자와의 연산도 가능하지만 파이썬 리스트는 불가능
    - 파이썬 리스트 : 곱셈으로 리스트 요소를 반복하는 것은 가능
 
- 사용 용도
    - 파이썬 리스트는 값을 추가하거나 제거하는 일에 사용
    - 넘파이 배열은 수치 계산이 많고 복잡하거나 다차원 배열이 필요할 때 사용

### 전치 연산(transpose)

- 2차원 배열의 행과 열을 바꾸는 연산

In [65]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

In [66]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [67]:
arr.shape

(2, 3)

In [68]:
# 전치
arr.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [69]:
arr.T.shape

(3, 2)

### 배열 크기 변형

In [70]:
arr1 = np.arange(12)

In [71]:
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [76]:
arr2 = arr1.reshape(3, 4)

In [77]:
arr2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

- 사용하는 원소의 수가 정해져 있기 때문에 reshape 의 형태 원소 중 하나는 -1로 대체할 수 있음

In [87]:
arr1.reshape(3, -1)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [85]:
arr1.reshape(2, 2, -1)

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [80]:
arr1.reshape(2, -1, 2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

# 넘파이 함수의 특징

- 벡터화 연산
    - 벡터와 행렬의 연산은 구성하는 원소별로 처리하는 것이 보통
    - 동일한 인덱스의 원소끼리 계산을 처리하는 것을 벡터화 연산이라고 함
 
- 유니버설 함수(universal function)
    - 벡터화 연산을 지원하는 특별한 함수를 유니버설 함수라고 함

In [88]:
# 일반 파이썬 함수의 타입 확인
def test():
    pass

In [89]:
type(test)

function

In [90]:
# 유니버설 함수 확인
type(np.add)

numpy.ufunc

In [92]:
# 넘파이 모듈에는 유니버설 함수도 있고 일반 함수도 있음
type(np.sort)

numpy._ArrayFunctionDispatcher

In [94]:
list2d + list2d

[[1, 2, 3], [4, 5, 6], [1, 2, 3], [4, 5, 6]]

In [95]:
np.add(list2d, list2d)

array([[ 2,  4,  6],
       [ 8, 10, 12]])

## 벡터화 연산

- 예) data 리스트 내의 각 값에 2를 곱해야 하는 경우

In [96]:
# 리스트를 통한 풀이
data = list(range(10))

In [97]:
data

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [98]:
data * 2

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [99]:
ans = []

for i in data:
    ans.append(i * 2)

ans

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [100]:
# 넘파이를 통한 풀이
data = np.array(data)

In [101]:
data * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

### 넘파이 벡터화 연산

- 벡터화 연산은 비교 연산과 논리 연산을 포함한 모든 종류의 수학 연산에 대해 적용됨

In [102]:
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])

In [103]:
a

array([1, 2, 3])

In [104]:
b

array([10, 20, 30])

In [105]:
2 * a + b

array([12, 24, 36])

In [106]:
a == 2

array([False,  True, False])

In [107]:
b > 10

array([False,  True,  True])

In [108]:
(a == 2) & (b > 10)

array([False,  True, False])

In [109]:
a[a == 2]

array([2])

- 배열끼리의 연산

In [110]:
arr1 = np.arange(6, 10)

In [111]:
arr1

array([6, 7, 8, 9])

In [112]:
arr2 = np.arange(10, 14)

In [113]:
arr2

array([10, 11, 12, 13])

In [114]:
# 두 개의 다차원 배열을 곱하면 동일한 인덱스의 원소끼리 곱셈한 결과인 1차원 배열이 반환됨
arr1 * arr2

array([ 60,  77,  96, 117])

In [115]:
# arr1 에 차원 추가(수직축 추가)
new_arr1 = arr1.reshape(-1, 1)

In [116]:
new_arr1

array([[6],
       [7],
       [8],
       [9]])

In [117]:
new_arr1.shape

(4, 1)

In [118]:
# arr2 에 차원 추가(수평축 추가)
new_arr2 = arr2.reshape(1, -1)

In [119]:
new_arr2

array([[10, 11, 12, 13]])

In [120]:
new_arr2.shape

(1, 4)

In [121]:
# 배열 곱 연산
new_arr1 * new_arr2

array([[ 60,  66,  72,  78],
       [ 70,  77,  84,  91],
       [ 80,  88,  96, 104],
       [ 90,  99, 108, 117]])

In [122]:
# 행렬곱 연산
new_arr1 @ new_arr2

array([[ 60,  66,  72,  78],
       [ 70,  77,  84,  91],
       [ 80,  88,  96, 104],
       [ 90,  99, 108, 117]])

In [123]:
a = np.array([[1, 2],
              [3, 4]])
b = np.array([[5, 6],
              [7, 8]])

In [124]:
# * 연산자는 요소별 곱셈을 수행
a * b

array([[ 5, 12],
       [21, 32]])

In [125]:
# @ 연산자는 행렬 곱을 수행
a @ b

array([[19, 22],
       [43, 50]])

## 브로드캐스팅(broadcasting)

- 배열끼리 연산을 하기 위해서는 두 배열의 크기가 같아야 함

- 서로 다른 크기를 가진 배열의 사칙 연산을 하는 경우 넘파이에서는 크기가 작은 배열을 자동으로 반복 확장하여 크기가 큰 배열에 맞춤

In [126]:
new_arr1

array([[6],
       [7],
       [8],
       [9]])

In [127]:
new_arr2

array([[10, 11, 12, 13]])

In [128]:
new_arr1 + new_arr2

array([[16, 17, 18, 19],
       [17, 18, 19, 20],
       [18, 19, 20, 21],
       [19, 20, 21, 22]])

- 연습문제

1. 아래의 배열에서 3의 배수를 찾기

2. 아래의 배열에서 4로 나누면 1이 남는 수를 찾기

3. 아래의 배열에서 3으로 나누면 나누어지고 4로 나누면 1이 남는 수를 찾기

In [129]:
x = np.arange(1, 21)

In [130]:
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [133]:
# 1. 아래의 배열에서 3의 배수를 찾기
x[x % 3 == 0]

array([ 3,  6,  9, 12, 15, 18])

In [136]:
# 2. 아래의 배열에서 4로 나누면 1이 남는 수를 찾기
x[x % 4 == 1]

array([ 1,  5,  9, 13, 17])

In [141]:
# 3. 아래의 배열에서 3으로 나누면 나누어지고 4로 나누면 1이 남는 수를 찾기
x[(x % 3 == 0) & (x % 4 == 1)]

array([9])

## 축에 따른 연산

- 동일한 축에 있는 원소들을 계산하기 위해서 필요함

In [142]:
# 1차원 배열
arr1 = np.array([1, 2, 3, 4])

In [143]:
arr1

array([1, 2, 3, 4])

In [144]:
# 합계
np.sum(arr1)

10

In [145]:
arr1.sum()

10

In [146]:
# 최댓값
arr1.max()

4

In [147]:
# 최솟값
arr1.min()

1

In [148]:
# 최솟값의 위치
arr1.argmin()

0

In [149]:
# 최댓값의 위치
arr1.argmax()

3

In [150]:
# 평균
arr1.mean()

2.5

In [151]:
# 중앙값
np.median(arr1)

2.5

In [152]:
# 2차원 배열
arr2 = arr1.reshape(2, 2)

In [153]:
arr2

array([[1, 2],
       [3, 4]])

In [154]:
# 모든 원소를 더한 합
np.sum(arr2)

10

In [155]:
# 수직방향으로 같은 열에 속한 원소만 합산
np.sum(arr2, axis = 0)

array([4, 6])

In [156]:
# 수평방향으로 같은 행에 속한 원소만 합산
np.sum(arr2, axis = 1)

array([3, 7])

In [157]:
arr3 = np.random.randint(0, 3, (2, 3))

In [158]:
arr3

array([[0, 2, 2],
       [1, 1, 0]])

In [159]:
np.sum(arr3)

6

In [160]:
np.sum(arr3, axis = 0)

array([1, 3, 2])

In [161]:
np.sum(arr3, axis = 1)

array([4, 2])

In [162]:
# 3차원배열
arr4 = np.arange(1, 9)

In [163]:
arr4

array([1, 2, 3, 4, 5, 6, 7, 8])

In [165]:
arr5 = arr4.reshape(2, 2, 2)

In [166]:
arr5

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [167]:
# 모든 원소를 더한 합
np.sum(arr5)

36

In [168]:
# 두 개의 행렬의 동일한 인덱스의 원소를 합한 값
np.sum(arr5, axis = 0)

array([[ 6,  8],
       [10, 12]])

In [169]:
# 각 2차원 배열의 열의 합
np.sum(arr5, axis = 1)

array([[ 4,  6],
       [12, 14]])

In [170]:
# 각 2차원 배열의 행의 합
np.sum(arr5, axis = 2)

array([[ 3,  7],
       [11, 15]])

In [171]:
np.sum(arr5, axis = (0, 1))

array([16, 20])

In [172]:
np.sum(arr5, axis = (0, 2))

array([14, 22])

In [173]:
np.sum(arr5, axis = (1, 2))

array([10, 26])

In [174]:
arr6 = np.random.randint(0, 3, (2, 3, 4))

In [175]:
arr6

array([[[1, 0, 0, 1],
        [2, 1, 2, 0],
        [1, 2, 1, 0]],

       [[0, 0, 0, 2],
        [2, 1, 0, 0],
        [0, 0, 0, 2]]])

In [176]:
np.sum(arr6, axis = 0 )

array([[1, 0, 0, 3],
       [4, 2, 2, 0],
       [1, 2, 1, 2]])

In [177]:
np.sum(arr6, axis = 1)

array([[4, 3, 3, 1],
       [2, 1, 0, 4]])

In [178]:
np.sum(arr6, axis = 2)

array([[2, 5, 4],
       [2, 3, 2]])

In [179]:
np.sum(arr6, axis = (0, 1))

array([6, 4, 3, 5])

In [180]:
np.sum(arr6, axis = (0, 2))

array([4, 8, 6])

In [181]:
np.sum(arr6, axis = (1, 2))

array([11,  7])

- 연습문제

    - 실수로 이루어진 5 x 6 형태의 데이터행렬에서 다음의 값을 구하기
    1. 전체의 최댓값
 
    2. 각 행의 합
 
    3. 각 행의 최댓값
 
    4. 각 열의 평균
 
    5. 각 열의 최솟값

In [182]:
x = np.random.random((5, 6))

In [183]:
x

array([[0.88496962, 0.94547027, 0.19790391, 0.31519035, 0.04802272,
        0.76409781],
       [0.99483811, 0.97379205, 0.67627995, 0.68706777, 0.58675935,
        0.42253889],
       [0.24340763, 0.84163185, 0.75831677, 0.98443391, 0.8947432 ,
        0.8194034 ],
       [0.8028178 , 0.18076112, 0.93923563, 0.21580778, 0.01706287,
        0.05307715],
       [0.29862463, 0.36645373, 0.71017424, 0.28210372, 0.5657446 ,
        0.49270491]])

In [184]:
# 1. 전체의 최댓값
x.max()

0.9948381059604376

In [185]:
x.argmax()

6

In [186]:
# 2. 각 행의 합
x.sum(axis = 1)

array([3.15565467, 4.34127611, 4.54193676, 2.20876234, 2.71580584])

In [187]:
# 3. 각 행의 최댓값
x.max(axis = 1)

array([0.94547027, 0.99483811, 0.98443391, 0.93923563, 0.71017424])

In [188]:
# 4. 각 열의 평균
x.mean(axis = 0)

array([0.64493156, 0.6616218 , 0.6563821 , 0.49692071, 0.42246655,
       0.51036443])

In [189]:
# 5. 각 열의 최솟값
x.min(axis = 0)

array([0.24340763, 0.18076112, 0.19790391, 0.21580778, 0.01706287,
       0.05307715])

# Inf 와 nan

- 넘파이에서는 무한대를 표현하기 위한 np.inf 와 정의할 수 없는 숫자를 나타내는 np.nan 이 있음

In [193]:
np.array([0, 1, -1, 0]) / np.array([1, 0, 0, 0])

C:\Users\ITSC\AppData\Local\Temp\ipykernel_12088\2068585620.py:1: RuntimeWarning: divide by zero encountered in divide
  np.array([0, 1, -1, 0]) / np.array([1, 0, 0, 0])
C:\Users\ITSC\AppData\Local\Temp\ipykernel_12088\2068585620.py:1: RuntimeWarning: invalid value encountered in divide
  np.array([0, 1, -1, 0]) / np.array([1, 0, 0, 0])


array([  0.,  inf, -inf,  nan])

# 스칼라와 벡터

- 벡터와 행렬은 특정 텐서(tensor) 를 부르는 이름

- 텐서의 이름을 부여하는 원칙은 차원인 축(axis)을 기준으로 지정
    - 텐서가 0차원인 경우(축이 없는 경우) : 스칼라(scalar)
    - 1차원인 경우 : 벡터(vector)
    - 2차원인 경우 : 행렬(matrix)
    - 3차원인 경우 : 큐브(cube) 또는 3차원 텐서
    - 더 차원이 높은 경우는 차원을 기준으로 n차원 텐서 라고 부름

## 스칼라

- 0차원 배열

- 크기를 표현

- 가장 기본적인 값

- 수학에서 배운 정수나 실수는 하나의 물리량인 크기를 표현하는데, 이 값을 스칼라 라고 함

In [194]:
scalar_arr = np.array(43)

In [196]:
# array 에서 스칼라는 대괄호 없이 숫자만 표시
# 대괄호는 벡터(1차원 배열) 부터 사용
scalar_arr

array(43)

In [197]:
type(scalar_arr)

numpy.ndarray

In [199]:
# 스칼라는 0차원
scalar_arr.ndim

0

In [201]:
# 축이 없기 때문에 빈 튜플
scalar_arr.shape

()

In [202]:
# array로 스칼라를 만들어도 dtype을 가짐
scalar_arr.dtype

dtype('int32')

## 벡터

- 1차원 배열

In [203]:
vector = np.array([43])

In [204]:
vector

array([43])

In [205]:
type(vector)

numpy.ndarray

In [206]:
# 1차원 배열
vector.ndim

1

In [207]:
vector.shape

(1,)

## 배열 생성 함수

### zeros

- 크기가 정해져 있고 모든 값이 0인 배열 생성

- 인수로는 배열의 크기를 전달

In [208]:
# 1차원 배열
zero_arr = np.zeros(5)

In [209]:
zero_arr

array([0., 0., 0., 0., 0.])

In [210]:
# 2차원 배열
zero_arr2 = np.zeros((2, 3))

In [211]:
zero_arr2

array([[0., 0., 0.],
       [0., 0., 0.]])

- dtype 인수를 명시하면 해당 자료형 원소 배열을 생성

In [212]:
zero_arr3 = np.zeros((5, 2), dtype = int)

In [213]:
zero_arr3

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 0]])

### ones

- 모든 값이 1인 배열 생성

In [218]:
one_arr = np.ones((2, 3, 4), dtype = int)

In [219]:
one_arr

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

### zeros_like, ones_like

- 다른 배열과 같은 크기의 배열을 생성

In [220]:
zero_arr4 = np.zeros_like(one_arr)

In [221]:
zero_arr4

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]])

In [222]:
one_arr2 = np.ones_like(zero_arr3)

In [223]:
one_arr2

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

In [224]:
np.ones_like(zero_arr2)

array([[1., 1., 1.],
       [1., 1., 1.]])

### arange

- 파이썬의 range와 유사한 함수

- range 와 같이 시작점, 종료점, 증감값 을 인자로 전달
    - 종료점은 필수

In [225]:
vector = np.arange(10)

In [226]:
vector

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [227]:
vector.dtype

dtype('int32')

- 인자로 실수를 지정할 수 있음

In [229]:
vector1 = np.arange(10.5, 20.5, 0.5)

In [230]:
vector1

array([10.5, 11. , 11.5, 12. , 12.5, 13. , 13.5, 14. , 14.5, 15. , 15.5,
       16. , 16.5, 17. , 17.5, 18. , 18.5, 19. , 19.5, 20. ])

In [231]:
vector1.dtype

dtype('float64')

In [232]:
# 원소의 개수
vector1.size

20

In [233]:
# 1차원 배열을 생성하면서 바로 2차원 배열로 형상 변경
vector2 = np.arange(60).reshape(6, 10)

In [234]:
vector2

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [235]:
vector2.shape

(6, 10)

In [236]:
# 1차원 배열을 생성하면서 3차원 배열로 형상 변경
vector3 = np.arange(60).reshape(3, 4, 5)

In [237]:
vector3

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]]])

### linspace

- arange 와의 차이점
    - 종료점도 포함해서 원소를 생성
 
    - 세 번째 인자로 간격 대신 원소의 개수를 전달
        - 초기값은 50
     
    - 기본으로 실수를 가진 원소를 만듦

In [238]:
lin = np.linspace(1, 10, 10)

In [239]:
lin

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [240]:
lin.dtype

dtype('float64')

In [241]:
# 값의 간격을 표시하는 증분(incremental) 을 확인할 수 있음
lin2 = np.linspace(1, 2, 10, retstep = True)

In [242]:
lin2

(array([1.        , 1.11111111, 1.22222222, 1.33333333, 1.44444444,
        1.55555556, 1.66666667, 1.77777778, 1.88888889, 2.        ]),
 0.1111111111111111)

In [243]:
# 종료값을 제외할 수도 있음
lin3 = np.linspace(1, 10, 10, endpoint = False, retstep = True)

In [244]:
lin3

(array([1. , 1.9, 2.8, 3.7, 4.6, 5.5, 6.4, 7.3, 8.2, 9.1]), 0.9)

## 벡터의 크기 및 단위 벡터 구하기

- 선형대수의 벡터는 크기와 방향을 가짐

- 벡터의 크기는 노름(norm) 이라고 부름

- 벡터는 평면 좌표의 점을 표시하듯이 2개의 원소를 가진 것을 대표적으로 사용
    - 벡터의 크기는 피타고라스의 정리를 사용

### 벡터의 크기 계산

In [245]:
# 두 개의 원소를 가지는 1차원 배열 생성
v = np.arange(3, 5)
v

array([3, 4])

In [250]:
# 벡터의 크기를 구하기 위해 각 원소를 제곱하여 합산한 후 제곱근 계산
v_p = np.power(v, 2)

In [251]:
v_p

array([ 9, 16], dtype=int32)

In [253]:
v_r = np.sqrt(np.sum(v_p))
v_r

5.0

In [254]:
# 피타고라스 정리를 구하는 hypot 함수를 사용할 수도 있음
np.hypot(v[0], v[1])

5.0

In [255]:
# 더 많은 원소를 가진 벡터를 가지고 크기를 구할 때는 np.linalg.norm 함수를 사용하면 간단함
np.linalg.norm(v)

5.0

### 단위 벡터(unit vector)

- 벡터의 크기가 항상 1인 경우를 단위 벡터 라고 함

- 표준 단위벡터(standard unit vector)는 원소 중에 하나가 1이고 나머지 원소가 0인 경우

In [256]:
# 표준 단위벡터 예시
e1 = np.array([1, 0, 0])
print(np.linalg.norm(e1))

1.0


In [257]:
e2 = np.array([0, 1, 0])
print(np.linalg.norm(e2))

1.0


In [258]:
e3 = np.array([0, 0, 1])
print(np.linalg.norm(e3))

1.0


- 일반적인 단위 벡터를 구할 때는 벡터의 크기를 구하고 각 원소를 벡터의 크기로 나누어서 구함

In [260]:
# 1차원 배열을 생성하고 이 배열의 크기를 계산
v_3 = np.array([1, 2, 3])
v_3

array([1, 2, 3])

In [261]:
v_3_n = np.linalg.norm(v_3)
v_3_n

3.7416573867739413

In [263]:
# 해당 벡터를 벡터의 크기로 나눈 후에 norm을 계산하면 1이 나옴
v_3_u = v_3 / v_3_n
v_3_u

array([0.26726124, 0.53452248, 0.80178373])

In [265]:
# 벡터의 크기가 1인 경우를 단위벡터라고 함
np.linalg.norm(v_3_u)

1.0

# 행렬(Matrix)

- 벡터는 하나의 차원이 축을 가져서 1차원 배열로 표시했지만 행렬은 두 개의 축인 차원을 가짐
    - 이 차원의 수평 방향을 행(row), 수직 방향을 열(column)이라고 함
 
- 보통 선형대수는 대괄호 내에 행과 열의 인덱스 위치에 숫자를 나열해서 표시

- 행렬을 부를 때는 보통 m개 행, n개 열로 이루어져서 m x n 행렬이라고 함

In [266]:
a = np.array([[43], [44]])

In [267]:
a

array([[43],
       [44]])

In [268]:
type(a)

numpy.ndarray

In [269]:
# a 변수에 저장된 배열도 하나의 배열이므로 하나의 자료형을 가짐
a.dtype

dtype('int32')

In [270]:
# 배열의 차원 확인
a.ndim

2

In [271]:
a.shape

(2, 1)

In [275]:
# np.full(형상, 채워질 값, 자료형) : 다차원 배열의 원소의 값을 동일하게 채움
b = np.full((3, 4), 7, int)
b

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])